### ISSUE TITLE
The following error occurred while running the code: AttributeError: 'NoneType' object has no attribute '__array_interface__'

### ISSUE THREAD

**Issue by Zhao-jiaxuan** [liyongqi67/MMCoQA#4]
In ./retriever_utils.py, the two _image_transform() methods seem to have some problems? In addition, can you update the python parameter settings during training? Hope to get your reply, thank you very much! 

The error message during running train_retriever.py is as follows: 
ibpng warning: iCCP: known incorrect sRGB profile
Evaluating:  80%|████████████████████████████████████████████████████████████████████████████████▊                    | 595/744 [44:13<11:04,  4.46s/it]
Traceback (most recent call last):
  File "train_retriever.py", line 820, in <module>
    result = evaluate(args, model, tokenizer, prefix=global_step)
  File "train_retriever.py", line 261, in evaluate
    passage_ids, passage_reps = gen_passage_rep(args, model, tokenizer)
  File "train_retriever.py", line 337, in gen_passage_rep
    for batch in tqdm(eval_dataloader, desc="Evaluating"):
  File "/data2/zjx/anaconda3/envs/mmcoqa/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/data2/zjx/anaconda3/envs/mmcoqa/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/data2/zjx/anaconda3/envs/mmcoqa/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/data2/zjx/anaconda3/envs/mmcoqa/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/data2/zjx/anaconda3/envs/mmcoqa/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/home/zjx/MMCoQA-main/retriever_utils.py", line 339, in _image_transform
    img = Image.fromarray(img)
  File "/data2/zjx/anaconda3/envs/mmcoqa/lib/python3.8/site-packages/PIL/Image.py", line 3069, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data2/zjx/anaconda3/envs/mmcoqa/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/data2/zjx/anaconda3/envs/mmcoqa/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data2/zjx/anaconda3/envs/mmcoqa/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zjx/MMCoQA-main/retriever_utils.py", line 382, in __getitem__
    img = self._image_transform(image_path)
  File "/home/zjx/MMCoQA-main/retriever_utils.py", line 342, in _image_transform
    img = Image.fromarray(cv2.imread(
  File "/data2/zjx/anaconda3/envs/mmcoqa/lib/python3.8/site-packages/PIL/Image.py", line 3069, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'

**Comment by liyongqi67** [comment]
I just updated the running steps. In case of any other queries, please do not hesitate to email me directly as I do not frequently check GitHub issues.

**Comment by liyongqi67** [comment]
Reopen this issue if have other problems
